# Generated by Django 3.0.5 on 2020-04-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('logo', models.CharField(blank=True, max_length=256)),
                ('desc', models.TextField()),
                ('employee_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=32)),
                ('picture', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('skills', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('published_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='junvac.Company')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='junvac.Speciality')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='vacancies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='junvac.Vacancy'),
        ),
    ]
