# Generated by Django 3.0.5 on 2020-04-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junvac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
