# Generated by Django 3.0.5 on 2020-04-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junvac', '0002_auto_20200407_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
